-- Seed Data: Channel Configs + Initial Knowledge Base
-- Note: Knowledge base embeddings are placeholder zeros;
-- run the embedding generation script to populate real vectors.

-- Channel configurations (G7, G8 compliance)
INSERT INTO channel_configs (channel, tone, max_length, greeting_template, signature_template) VALUES
('gmail', 'formal', 500, 'Dear {customer_name},', E'Best regards,\nStreamLine Support Team\nsupport@streamline-saas.com'),
('whatsapp', 'conversational', 300, 'Hi {customer_name}! 👋', NULL),
('webform', 'semi-formal', 1000, 'Hello {customer_name},', NULL);

-- Initial knowledge base entries (seed)
-- Embeddings are zero vectors as placeholders — generate real embeddings on first run
INSERT INTO knowledge_base (title, content, category, embedding, source) VALUES
('How to reset password', 'Go to Settings → Security → Change Password. You can also click "Forgot Password" on the login page to receive a reset link via email.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('File upload not working', 'Check that your file is under 100MB. Try using Chrome or Edge browser. Clear your browser cache and retry. If the issue persists, try a different file format.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to invite team members', 'Go to your workspace settings → Members → Invite. Enter team member email addresses. They will receive an invitation email. Note: Starter plan supports up to 5 users, Professional up to 50, Enterprise unlimited.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('Slow loading times', 'Try these steps: 1) Check your internet connection 2) Clear browser cache 3) Try a different browser 4) Disable browser extensions 5) If using VPN, try without it. If the problem continues, our engineering team is monitoring performance.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to create a project', 'Click the "+" button in the sidebar → Select "New Project" → Enter project name and description → Choose a template (Kanban, Scrum, or Blank) → Invite team members → Click Create.', 'general-question', array_fill(0, ARRAY[384])::vector, 'seed'),
('Notifications not working', 'Go to Settings → Notifications and verify that email and push notifications are enabled. Check your spam folder for notification emails. On mobile, ensure the StreamLine app has notification permissions in your device settings.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to export data', 'Go to Settings → Data → Export. Select the data type (tasks, time entries, or full workspace). Choose format (JSON or CSV). Click Export. Large exports may take up to 10 minutes — you will receive a download link via email.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('Integration with Slack', 'Go to Settings → Integrations → Slack → Connect. Authorize StreamLine to access your Slack workspace. Select which channels to sync. You can customize which events trigger Slack notifications.', 'feature-request', array_fill(0, ARRAY[384])::vector, 'seed'),
('Video call quality issues', 'For best video call quality: 1) Use Chrome or Edge browser 2) Close other video/audio apps 3) Ensure stable internet (minimum 5 Mbps) 4) Use a headset to reduce echo 5) Close unnecessary browser tabs. Maximum participants: 25.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to use Kanban board', 'Open your project → Click "Board" view in the top navigation. You will see columns: To Do, In Progress, Review, Done. Drag and drop tasks between columns to update their status. Click "+" at the top of any column to add a new task.', 'general-question', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to track time', 'Click the clock icon on any task to start the timer. It will track time automatically. To add time manually, click "Add Time Entry" on the task detail page. View reports under Reports → Time Tracking.', 'general-question', array_fill(0, ARRAY[384])::vector, 'seed'),
('Cannot log in to account', 'Try these steps: 1) Clear browser cache and cookies 2) Try incognito/private mode 3) Reset password via "Forgot Password" 4) Check if your account is active (no suspension email) 5) Try a different browser. If still unable, contact support with your registered email.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to use Gantt chart', 'Open your project → Click "Timeline" view. Tasks appear as horizontal bars on a timeline. Drag bar edges to change dates. Draw arrows between tasks to set dependencies. Use the zoom controls to switch between day/week/month view.', 'general-question', array_fill(0, ARRAY[384])::vector, 'seed'),
('GitHub integration setup', 'Go to Settings → Integrations → GitHub → Connect. Authorize StreamLine. Select repositories to link. Once connected, you can link pull requests to tasks. Tasks auto-update status when PRs are merged.', 'feature-request', array_fill(0, ARRAY[384])::vector, 'seed'),
('Task limit reached', 'The maximum is 1,000 tasks per project. To work around this: 1) Archive completed tasks 2) Split into multiple projects 3) Contact support to request a limit increase for Enterprise customers.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to set up 2FA', 'Go to Settings → Security → Two-Factor Authentication → Enable. Scan the QR code with your authenticator app (Google Authenticator, Authy, etc.). Enter the 6-digit code to confirm. Save your backup codes in a safe place.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('Mobile app crashing', 'Try these fixes: 1) Update to the latest app version from App Store/Play Store 2) Clear the app cache in device settings 3) Restart your device 4) Uninstall and reinstall the app. If the problem persists, please share your device model and OS version.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed'),
('Custom fields feature', 'Custom fields are available on Professional and Enterprise plans. Go to Project Settings → Custom Fields → Add Field. Choose field type (text, number, dropdown, date, checkbox). Custom fields appear on task detail pages and can be used in filters.', 'feature-request', array_fill(0, ARRAY[384])::vector, 'seed'),
('How to delete account', 'Go to Settings → Account → Delete Account. Note: This requires admin confirmation and has a 30-day grace period. All data will be permanently deleted after 30 days. Export your data first via Settings → Data → Export.', 'account-help', array_fill(0, ARRAY[384])::vector, 'seed'),
('API rate limiting', 'API rate limits: Professional plan — 100 requests/minute, Enterprise plan — 1,000 requests/minute. If you exceed the limit, you will receive a 429 status code. Implement exponential backoff in your integration. Contact support for Enterprise rate limit increases.', 'technical-issue', array_fill(0, ARRAY[384])::vector, 'seed');
